package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.DataVersions;
import com.rcloud.server.sealtalk.domain.DataVersionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataVersionsMapper {
    long countByExample(DataVersionsExample example);

    int deleteByExample(DataVersionsExample example);

    int deleteByPrimaryKey(Integer userId);

    int insert(DataVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") DataVersions record, @Param("selective") DataVersions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DataVersions selectOneByExample(DataVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DataVersions selectOneByExampleSelective(@Param("example") DataVersionsExample example, @Param("selective") DataVersions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DataVersions> selectByExampleSelective(@Param("example") DataVersionsExample example, @Param("selective") DataVersions.Column ... selective);

    List<DataVersions> selectByExample(DataVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DataVersions selectByPrimaryKeySelective(@Param("userId") Integer userId, @Param("selective") DataVersions.Column ... selective);

    DataVersions selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") DataVersions record, @Param("example") DataVersionsExample example, @Param("selective") DataVersions.Column ... selective);

    int updateByExample(@Param("record") DataVersions record, @Param("example") DataVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") DataVersions record, @Param("selective") DataVersions.Column ... selective);

    int updateByPrimaryKey(DataVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<DataVersions> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<DataVersions> list, @Param("selective") DataVersions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(DataVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") DataVersions record, @Param("example") DataVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") DataVersions record, @Param("example") DataVersionsExample example, @Param("selective") DataVersions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") DataVersions record, @Param("selective") DataVersions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<DataVersions> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_versions
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<DataVersions> list, @Param("selective") DataVersions.Column ... selective);
}