package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupBulletins;
import com.rcloud.server.sealtalk.domain.GroupBulletinsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupBulletinsMapper {
    long countByExample(GroupBulletinsExample example);

    int deleteByExample(GroupBulletinsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(GroupBulletins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupBulletins record, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBulletins selectOneByExample(GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBulletins selectOneByExampleSelective(@Param("example") GroupBulletinsExample example, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBulletins selectOneByExampleWithBLOBs(GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupBulletins> selectByExampleSelective(@Param("example") GroupBulletinsExample example, @Param("selective") GroupBulletins.Column ... selective);

    List<GroupBulletins> selectByExampleWithBLOBs(GroupBulletinsExample example);

    List<GroupBulletins> selectByExample(GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBulletins selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupBulletins.Column ... selective);

    GroupBulletins selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example, @Param("selective") GroupBulletins.Column ... selective);

    int updateByExampleWithBLOBs(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example);

    int updateByExample(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupBulletins record, @Param("selective") GroupBulletins.Column ... selective);

    int updateByPrimaryKeyWithBLOBs(GroupBulletins record);

    int updateByPrimaryKey(GroupBulletins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupBulletins> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupBulletins> list, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupBulletins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleWithBLOBs(@Param("record") GroupBulletins record, @Param("example") GroupBulletinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupBulletins record, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(GroupBulletins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupBulletins> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupBulletins> list, @Param("selective") GroupBulletins.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_bulletins
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertWithBLOBs(@Param("list") List<GroupBulletins> list);
}