package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupMembers;
import com.rcloud.server.sealtalk.domain.GroupMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMembersMapper {
    long countByExample(GroupMembersExample example);

    int deleteByExample(GroupMembersExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupMembers record, @Param("selective") GroupMembers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupMembers selectOneByExample(GroupMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupMembers selectOneByExampleSelective(@Param("example") GroupMembersExample example, @Param("selective") GroupMembers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupMembers> selectByExampleSelective(@Param("example") GroupMembersExample example, @Param("selective") GroupMembers.Column ... selective);

    List<GroupMembers> selectByExample(GroupMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupMembers selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupMembers.Column ... selective);

    GroupMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupMembers record, @Param("example") GroupMembersExample example, @Param("selective") GroupMembers.Column ... selective);

    int updateByExample(@Param("record") GroupMembers record, @Param("example") GroupMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupMembers record, @Param("selective") GroupMembers.Column ... selective);

    int updateByPrimaryKey(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupMembers> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupMembers> list, @Param("selective") GroupMembers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupMembers record, @Param("example") GroupMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupMembers record, @Param("example") GroupMembersExample example, @Param("selective") GroupMembers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupMembers record, @Param("selective") GroupMembers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupMembers> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupMembers> list, @Param("selective") GroupMembers.Column ... selective);
}