package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupReceivers;
import com.rcloud.server.sealtalk.domain.GroupReceiversExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupReceiversMapper {
    long countByExample(GroupReceiversExample example);

    int deleteByExample(GroupReceiversExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(GroupReceivers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupReceivers record, @Param("selective") GroupReceivers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupReceivers selectOneByExample(GroupReceiversExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupReceivers selectOneByExampleSelective(@Param("example") GroupReceiversExample example, @Param("selective") GroupReceivers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupReceivers> selectByExampleSelective(@Param("example") GroupReceiversExample example, @Param("selective") GroupReceivers.Column ... selective);

    List<GroupReceivers> selectByExample(GroupReceiversExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupReceivers selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupReceivers.Column ... selective);

    GroupReceivers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupReceivers record, @Param("example") GroupReceiversExample example, @Param("selective") GroupReceivers.Column ... selective);

    int updateByExample(@Param("record") GroupReceivers record, @Param("example") GroupReceiversExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupReceivers record, @Param("selective") GroupReceivers.Column ... selective);

    int updateByPrimaryKey(GroupReceivers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupReceivers> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupReceivers> list, @Param("selective") GroupReceivers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupReceivers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupReceivers record, @Param("example") GroupReceiversExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupReceivers record, @Param("example") GroupReceiversExample example, @Param("selective") GroupReceivers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupReceivers record, @Param("selective") GroupReceivers.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupReceivers> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_receivers
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupReceivers> list, @Param("selective") GroupReceivers.Column ... selective);
}