package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupFavs;
import com.rcloud.server.sealtalk.domain.GroupFavsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupFavsMapper {
    long countByExample(GroupFavsExample example);

    int deleteByExample(GroupFavsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(GroupFavs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupFavs record, @Param("selective") GroupFavs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupFavs selectOneByExample(GroupFavsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupFavs selectOneByExampleSelective(@Param("example") GroupFavsExample example, @Param("selective") GroupFavs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupFavs> selectByExampleSelective(@Param("example") GroupFavsExample example, @Param("selective") GroupFavs.Column ... selective);

    List<GroupFavs> selectByExample(GroupFavsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupFavs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupFavs.Column ... selective);

    GroupFavs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupFavs record, @Param("example") GroupFavsExample example, @Param("selective") GroupFavs.Column ... selective);

    int updateByExample(@Param("record") GroupFavs record, @Param("example") GroupFavsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupFavs record, @Param("selective") GroupFavs.Column ... selective);

    int updateByPrimaryKey(GroupFavs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupFavs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupFavs> list, @Param("selective") GroupFavs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupFavs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupFavs record, @Param("example") GroupFavsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupFavs record, @Param("example") GroupFavsExample example, @Param("selective") GroupFavs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupFavs record, @Param("selective") GroupFavs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupFavs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_favs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupFavs> list, @Param("selective") GroupFavs.Column ... selective);
}