package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupSyncs;
import com.rcloud.server.sealtalk.domain.GroupSyncsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupSyncsMapper {
    long countByExample(GroupSyncsExample example);

    int deleteByExample(GroupSyncsExample example);

    int deleteByPrimaryKey(Integer groupId);

    int insert(GroupSyncs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupSyncs record, @Param("selective") GroupSyncs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupSyncs selectOneByExample(GroupSyncsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupSyncs selectOneByExampleSelective(@Param("example") GroupSyncsExample example, @Param("selective") GroupSyncs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupSyncs> selectByExampleSelective(@Param("example") GroupSyncsExample example, @Param("selective") GroupSyncs.Column ... selective);

    List<GroupSyncs> selectByExample(GroupSyncsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupSyncs selectByPrimaryKeySelective(@Param("groupId") Integer groupId, @Param("selective") GroupSyncs.Column ... selective);

    GroupSyncs selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupSyncs record, @Param("example") GroupSyncsExample example, @Param("selective") GroupSyncs.Column ... selective);

    int updateByExample(@Param("record") GroupSyncs record, @Param("example") GroupSyncsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupSyncs record, @Param("selective") GroupSyncs.Column ... selective);

    int updateByPrimaryKey(GroupSyncs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupSyncs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupSyncs> list, @Param("selective") GroupSyncs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupSyncs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupSyncs record, @Param("example") GroupSyncsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupSyncs record, @Param("example") GroupSyncsExample example, @Param("selective") GroupSyncs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupSyncs record, @Param("selective") GroupSyncs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupSyncs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupSyncs> list, @Param("selective") GroupSyncs.Column ... selective);
}