package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.GroupExitedLists;
import com.rcloud.server.sealtalk.domain.GroupExitedListsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupExitedListsMapper {
    long countByExample(GroupExitedListsExample example);

    int deleteByExample(GroupExitedListsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(GroupExitedLists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupExitedLists record, @Param("selective") GroupExitedLists.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupExitedLists selectOneByExample(GroupExitedListsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupExitedLists selectOneByExampleSelective(@Param("example") GroupExitedListsExample example, @Param("selective") GroupExitedLists.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupExitedLists> selectByExampleSelective(@Param("example") GroupExitedListsExample example, @Param("selective") GroupExitedLists.Column ... selective);

    List<GroupExitedLists> selectByExample(GroupExitedListsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupExitedLists selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupExitedLists.Column ... selective);

    GroupExitedLists selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupExitedLists record, @Param("example") GroupExitedListsExample example, @Param("selective") GroupExitedLists.Column ... selective);

    int updateByExample(@Param("record") GroupExitedLists record, @Param("example") GroupExitedListsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupExitedLists record, @Param("selective") GroupExitedLists.Column ... selective);

    int updateByPrimaryKey(GroupExitedLists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupExitedLists> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupExitedLists> list, @Param("selective") GroupExitedLists.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GroupExitedLists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") GroupExitedLists record, @Param("example") GroupExitedListsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") GroupExitedLists record, @Param("example") GroupExitedListsExample example, @Param("selective") GroupExitedLists.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") GroupExitedLists record, @Param("selective") GroupExitedLists.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<GroupExitedLists> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_exited_lists
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<GroupExitedLists> list, @Param("selective") GroupExitedLists.Column ... selective);
}