package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.LoginLogs;
import com.rcloud.server.sealtalk.domain.LoginLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginLogsMapper {
    long countByExample(LoginLogsExample example);

    int deleteByExample(LoginLogsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") LoginLogs record, @Param("selective") LoginLogs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LoginLogs selectOneByExample(LoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LoginLogs selectOneByExampleSelective(@Param("example") LoginLogsExample example, @Param("selective") LoginLogs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LoginLogs> selectByExampleSelective(@Param("example") LoginLogsExample example, @Param("selective") LoginLogs.Column ... selective);

    List<LoginLogs> selectByExample(LoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LoginLogs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LoginLogs.Column ... selective);

    LoginLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") LoginLogs record, @Param("example") LoginLogsExample example, @Param("selective") LoginLogs.Column ... selective);

    int updateByExample(@Param("record") LoginLogs record, @Param("example") LoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") LoginLogs record, @Param("selective") LoginLogs.Column ... selective);

    int updateByPrimaryKey(LoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<LoginLogs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<LoginLogs> list, @Param("selective") LoginLogs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(LoginLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") LoginLogs record, @Param("example") LoginLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") LoginLogs record, @Param("example") LoginLogsExample example, @Param("selective") LoginLogs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") LoginLogs record, @Param("selective") LoginLogs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<LoginLogs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_logs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<LoginLogs> list, @Param("selective") LoginLogs.Column ... selective);
}