package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.ScreenStatuses;
import com.rcloud.server.sealtalk.domain.ScreenStatusesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScreenStatusesMapper {
    long countByExample(ScreenStatusesExample example);

    int deleteByExample(ScreenStatusesExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ScreenStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") ScreenStatuses record, @Param("selective") ScreenStatuses.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ScreenStatuses selectOneByExample(ScreenStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ScreenStatuses selectOneByExampleSelective(@Param("example") ScreenStatusesExample example, @Param("selective") ScreenStatuses.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ScreenStatuses> selectByExampleSelective(@Param("example") ScreenStatusesExample example, @Param("selective") ScreenStatuses.Column ... selective);

    List<ScreenStatuses> selectByExample(ScreenStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ScreenStatuses selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ScreenStatuses.Column ... selective);

    ScreenStatuses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") ScreenStatuses record, @Param("example") ScreenStatusesExample example, @Param("selective") ScreenStatuses.Column ... selective);

    int updateByExample(@Param("record") ScreenStatuses record, @Param("example") ScreenStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") ScreenStatuses record, @Param("selective") ScreenStatuses.Column ... selective);

    int updateByPrimaryKey(ScreenStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<ScreenStatuses> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<ScreenStatuses> list, @Param("selective") ScreenStatuses.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(ScreenStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") ScreenStatuses record, @Param("example") ScreenStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") ScreenStatuses record, @Param("example") ScreenStatusesExample example, @Param("selective") ScreenStatuses.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") ScreenStatuses record, @Param("selective") ScreenStatuses.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<ScreenStatuses> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_statuses
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<ScreenStatuses> list, @Param("selective") ScreenStatuses.Column ... selective);
}