package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.VerificationCodes;
import com.rcloud.server.sealtalk.domain.VerificationCodesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerificationCodesMapper {
    long countByExample(VerificationCodesExample example);

    int deleteByExample(VerificationCodesExample example);

    int deleteByPrimaryKey(@Param("id") Integer id, @Param("region") String region, @Param("phone") String phone);

    int insert(VerificationCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") VerificationCodes record, @Param("selective") VerificationCodes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationCodes selectOneByExample(VerificationCodesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationCodes selectOneByExampleSelective(@Param("example") VerificationCodesExample example, @Param("selective") VerificationCodes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<VerificationCodes> selectByExampleSelective(@Param("example") VerificationCodesExample example, @Param("selective") VerificationCodes.Column ... selective);

    List<VerificationCodes> selectByExample(VerificationCodesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationCodes selectByPrimaryKeySelective(@Param("id") Integer id, @Param("region") String region, @Param("phone") String phone, @Param("selective") VerificationCodes.Column ... selective);

    VerificationCodes selectByPrimaryKey(@Param("id") Integer id, @Param("region") String region, @Param("phone") String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") VerificationCodes record, @Param("example") VerificationCodesExample example, @Param("selective") VerificationCodes.Column ... selective);

    int updateByExample(@Param("record") VerificationCodes record, @Param("example") VerificationCodesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") VerificationCodes record, @Param("selective") VerificationCodes.Column ... selective);

    int updateByPrimaryKey(VerificationCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<VerificationCodes> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<VerificationCodes> list, @Param("selective") VerificationCodes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(VerificationCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") VerificationCodes record, @Param("example") VerificationCodesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") VerificationCodes record, @Param("example") VerificationCodesExample example, @Param("selective") VerificationCodes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") VerificationCodes record, @Param("selective") VerificationCodes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<VerificationCodes> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_codes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<VerificationCodes> list, @Param("selective") VerificationCodes.Column ... selective);
}