package com.rcloud.server.sealtalk.dao;

import com.rcloud.server.sealtalk.domain.VerificationViolations;
import com.rcloud.server.sealtalk.domain.VerificationViolationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerificationViolationsMapper {
    long countByExample(VerificationViolationsExample example);

    int deleteByExample(VerificationViolationsExample example);

    int deleteByPrimaryKey(String ip);

    int insert(VerificationViolations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") VerificationViolations record, @Param("selective") VerificationViolations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationViolations selectOneByExample(VerificationViolationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationViolations selectOneByExampleSelective(@Param("example") VerificationViolationsExample example, @Param("selective") VerificationViolations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<VerificationViolations> selectByExampleSelective(@Param("example") VerificationViolationsExample example, @Param("selective") VerificationViolations.Column ... selective);

    List<VerificationViolations> selectByExample(VerificationViolationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VerificationViolations selectByPrimaryKeySelective(@Param("ip") String ip, @Param("selective") VerificationViolations.Column ... selective);

    VerificationViolations selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") VerificationViolations record, @Param("example") VerificationViolationsExample example, @Param("selective") VerificationViolations.Column ... selective);

    int updateByExample(@Param("record") VerificationViolations record, @Param("example") VerificationViolationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") VerificationViolations record, @Param("selective") VerificationViolations.Column ... selective);

    int updateByPrimaryKey(VerificationViolations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<VerificationViolations> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<VerificationViolations> list, @Param("selective") VerificationViolations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(VerificationViolations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") VerificationViolations record, @Param("example") VerificationViolationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") VerificationViolations record, @Param("example") VerificationViolationsExample example, @Param("selective") VerificationViolations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") VerificationViolations record, @Param("selective") VerificationViolations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<VerificationViolations> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_violations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<VerificationViolations> list, @Param("selective") VerificationViolations.Column ... selective);
}