package com.rcloud.server.sealtalk.domain;

import java.util.ArrayList;
import java.util.List;

public class GroupSyncsExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public GroupSyncsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GroupSyncsExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GroupSyncsExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GroupSyncsExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GroupSyncsExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GroupSyncsExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_syncs
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        GroupSyncsExample example = new GroupSyncsExample();
        return example.createCriteria();
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("groupId is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("groupId is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("groupId =", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("groupId <>", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdNotEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("groupId >", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdGreaterThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("groupId >=", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdGreaterThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("groupId <", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdLessThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("groupId <=", value, "groupId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andGroupIdLessThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("groupId <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("groupId in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("groupId not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("groupId between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("groupId not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andSyncInfoIsNull() {
            addCriterion("syncInfo is null");
            return (Criteria) this;
        }

        public Criteria andSyncInfoIsNotNull() {
            addCriterion("syncInfo is not null");
            return (Criteria) this;
        }

        public Criteria andSyncInfoEqualTo(Boolean value) {
            addCriterion("syncInfo =", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoNotEqualTo(Boolean value) {
            addCriterion("syncInfo <>", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoNotEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoGreaterThan(Boolean value) {
            addCriterion("syncInfo >", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoGreaterThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoGreaterThanOrEqualTo(Boolean value) {
            addCriterion("syncInfo >=", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoGreaterThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoLessThan(Boolean value) {
            addCriterion("syncInfo <", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoLessThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoLessThanOrEqualTo(Boolean value) {
            addCriterion("syncInfo <=", value, "syncInfo");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncInfoLessThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncInfo <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncInfoIn(List<Boolean> values) {
            addCriterion("syncInfo in", values, "syncInfo");
            return (Criteria) this;
        }

        public Criteria andSyncInfoNotIn(List<Boolean> values) {
            addCriterion("syncInfo not in", values, "syncInfo");
            return (Criteria) this;
        }

        public Criteria andSyncInfoBetween(Boolean value1, Boolean value2) {
            addCriterion("syncInfo between", value1, value2, "syncInfo");
            return (Criteria) this;
        }

        public Criteria andSyncInfoNotBetween(Boolean value1, Boolean value2) {
            addCriterion("syncInfo not between", value1, value2, "syncInfo");
            return (Criteria) this;
        }

        public Criteria andSyncMemberIsNull() {
            addCriterion("syncMember is null");
            return (Criteria) this;
        }

        public Criteria andSyncMemberIsNotNull() {
            addCriterion("syncMember is not null");
            return (Criteria) this;
        }

        public Criteria andSyncMemberEqualTo(Boolean value) {
            addCriterion("syncMember =", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberNotEqualTo(Boolean value) {
            addCriterion("syncMember <>", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberNotEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberGreaterThan(Boolean value) {
            addCriterion("syncMember >", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberGreaterThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberGreaterThanOrEqualTo(Boolean value) {
            addCriterion("syncMember >=", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberGreaterThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberLessThan(Boolean value) {
            addCriterion("syncMember <", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberLessThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberLessThanOrEqualTo(Boolean value) {
            addCriterion("syncMember <=", value, "syncMember");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSyncMemberLessThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("syncMember <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSyncMemberIn(List<Boolean> values) {
            addCriterion("syncMember in", values, "syncMember");
            return (Criteria) this;
        }

        public Criteria andSyncMemberNotIn(List<Boolean> values) {
            addCriterion("syncMember not in", values, "syncMember");
            return (Criteria) this;
        }

        public Criteria andSyncMemberBetween(Boolean value1, Boolean value2) {
            addCriterion("syncMember between", value1, value2, "syncMember");
            return (Criteria) this;
        }

        public Criteria andSyncMemberNotBetween(Boolean value1, Boolean value2) {
            addCriterion("syncMember not between", value1, value2, "syncMember");
            return (Criteria) this;
        }

        public Criteria andDismissIsNull() {
            addCriterion("dismiss is null");
            return (Criteria) this;
        }

        public Criteria andDismissIsNotNull() {
            addCriterion("dismiss is not null");
            return (Criteria) this;
        }

        public Criteria andDismissEqualTo(Boolean value) {
            addCriterion("dismiss =", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissNotEqualTo(Boolean value) {
            addCriterion("dismiss <>", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissNotEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissGreaterThan(Boolean value) {
            addCriterion("dismiss >", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissGreaterThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissGreaterThanOrEqualTo(Boolean value) {
            addCriterion("dismiss >=", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissGreaterThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissLessThan(Boolean value) {
            addCriterion("dismiss <", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissLessThanColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissLessThanOrEqualTo(Boolean value) {
            addCriterion("dismiss <=", value, "dismiss");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDismissLessThanOrEqualToColumn(GroupSyncs.Column column) {
            addCriterion(new StringBuilder("dismiss <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDismissIn(List<Boolean> values) {
            addCriterion("dismiss in", values, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotIn(List<Boolean> values) {
            addCriterion("dismiss not in", values, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissBetween(Boolean value1, Boolean value2) {
            addCriterion("dismiss between", value1, value2, "dismiss");
            return (Criteria) this;
        }

        public Criteria andDismissNotBetween(Boolean value1, Boolean value2) {
            addCriterion("dismiss not between", value1, value2, "dismiss");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GroupSyncsExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(GroupSyncsExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GroupSyncsExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table group_syncs
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table group_syncs
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}